app:
  config:
    routesPath: "classpath:routes.json"
    pointGenerationIntervalMs: ${ENV_GEN_INTERVAL:2000}
  kafka:
    bootstrapServers: ${ENV_BOOTSTRAP_SERVERS:localhost:1999}
    outputTopic:
      name: "route_points_live"
      partitions: 1
      replication: 1
      properties:
        retentionMs: "259200000"
        retentionBytes: "107374182"
        cleanupPolicy: "delete"