app:
  config:
    input_topic: "route_points_live"
    kafka:
      "[bootstrap.servers]": ${ENV_BOOTSTRAP_SERVERS:"localhost:1999,localhost:2999,localhost:3999"}
      "[key.deserializer]": "org.apache.kafka.common.serialization.StringDeserializer"
      "[value.deserializer]": "org.apache.kafka.common.serialization.StringDeserializer"
      "[auto.offset.reset]": "latest"
      "[client.id]": "live_route_client"
      "[group.id]": "live_route"
      "[max.poll.records]": 300
      "[enable.auto.commit]": true